### ISSUE TITLE
[REQ] Support for monitors with different resolutions

### ISSUE THREAD

**Issue by vanowm** [Jawfin/nsm#1]
Having monitors with different resolutions creates "dead end" corner on large monitor

![Imgur](http://i.imgur.com/zo8jYF1.png)

Would be nice if NSM translated cursor position based on percentage, so 0% = top and 100% bottom (assuming setup as per screenshot). I guess it called relative coordinates?
This way no matter at what coordinate cursor is leaving one monitor it will enter second monitor at relatively same point between top and bottom.

**Comment by Jawfin** [comment]
I suspect that's due to a very fine out-of-alignment issue.  You won't see it on the screen as Microsoft isn't showing the display monitors to that level of precision.
I recommend looking at this reply here and see if it helps: -
http://www.jawfin.net/?page_id=143&cpage=2#comment-15310

**Comment by vanowm** [comment]
Yes I saw that post and tried the debug tool.
The issue is not in monitors misalignment, but how windows is handling cursor coordinates.

My understanding is that NSM already changes cursor coordinates when it reaches certain points on screen, so it has the capability of recalculating coordinates when moving from one monitor to another. The formula is simple:
1) detect when cursor is about to reach edge of screen
2) calculate at what % from the top it will be at: P = Y * 100 / H1
3) calculate what is Y coordinates on next monitor: Y = P * H2 / 100

H1 = height of first monitor
H2 = height of second monitor

This will eliminate misalignment issue all together.


I understand this might bring some other issues, for example when moving a window would make it "jump" when cursor crosses over the screen, because window will be shown on both screen at some point, it will change coordinate once cursor crossed to another monitor, but I think it's still doable.

**Comment by Jawfin** [comment]
Oh, I'm sorry - I see what you're saying!  I'll have to look into this for you.
If you're a programmer or can follow the code and want to have a crack at it too, please feel free.  I can compile any requested changes if you don't have a copy of Delphi.
I only mention this as I am swamped with work and sad to say this isn't as high on my radar as I would like :(

**Comment by Jawfin** [comment]
I've installed the latest Creator patch, version 1703 (OS Build 15063.138) and tried to duplicate the behaviour you're seeing but could not achieve it sorry :\
Its possible some work I've done in the app bypassed / fixed it, if so try the latest release: -
http://www.jawfin.net/nsm
And I'll update my source code here with that too.

Edit: re-reading your request it would seem that you don;t want it to work on absolute positioning - which is to say to change the behaviour of how Microsoft handles the cursor placement between monitors.  Is that correct?  I don't intend to change something like that, I'm just trying to hop the mouse jamming.  If you want that though I can write you a specific application to do so.  Please let me know if I have misunderstood here!!  Cheers

**Comment by vanowm** [comment]
Yes, you understood it correctly.

![relative path](https://cloud.githubusercontent.com/assets/511517/25370341/0a3baa1e-2958-11e7-8f4b-e94c9dcb6e86.png)


Basically the idea is if you have 2 monitors with physically identical height, but different resolution, sitting side by side, moving cursor between monitors it would feel like monitors have identical resolution, because visually cursor would show up on next monitor at exactly same position as previous monitor. 
Currently if I move cursor from bottom of low res. monitor it shows up in the middle of high res. monitor, instead of bottom.

If you think you could create a separate program for that, it would be awesome!
Thank you.

**Comment by Jawfin** [comment]
Hmm, we may have a problem getting NSM to behave like this then.
The problems I have with it is I don't control the mouse, or watch where it's going, like interactive behaviour.  What it does is frequently check where it is, and if it's in a corner and last time checked it wasn't then it'll get popped over the screen.

The drawback with this working they way you need it to is that most of the time, say 90% the mouse manages to cross the screen border without knowledge or interference of NSM.  But for it to get re-positioned responsively on every border cross would require hooking the mouse movement.  Otherwise I dare suspect it will easily get confused, in that it may apply the ratio on the wrong screen - or for the most part do nothing (i.e. windows handles the cursor tracking and places it at its absolute location).

I did some looking around and see that applications specifically written for multiple monitors don't even handle this well: -
https://www.realtimesoft.com/multimon/forum/messages.asp?Topic=21405

Hooking the mouse driver is very intrusive, and will upset every virus scanner on the planet!  (Live injection of a dll into the Operating System itself, or a very aggressive [intercept everything] windows message handler.)  It may even require Ring 0 coding - which I won't do!

So that leaves us with making our NSM clone much smarter, and at least run at a higher CPU priority/affinity.
What I'd have to do is look at what screen its on, then what screen it's going to.  Compare the density of both and convert the coordinates to some common ground (like a float between 0 and 1) - and apply that back against the resolutions of both screens.  Then apply any offsets against that float (like the monitors aren't directly aligned).  With that the new relative mouse coordinates could be calculated for the next screen, multiplying out my relative values (the ones between 0 and 1) against the screen size - the new density should be factored in already.

This is a world away from what NSM does and what information is available to it.  I could hijack my debug version and make it a switch on the screen to attempt this.  Also note though, this will be very hard to test as I can't duplicate that setup, and wouldn't know if it worked.  I'm thinking this through and I don't think there's an easier way to work this out.

**Comment by vanowm** [comment]
I just found that [DisplayFusion](https://www.displayfusion.com) program which I've been using for ages has an option "Prevent mouse cursor from snagging on unaligned monitor edges".
It affects different sizes monitors as well, with only one issue: it simply moves cursor to the bottom of low res monitor if cursor is leaving high res monitor at larger coordinate then the max of low res monitor and when cursor is leaving low res monitor at the bottom edge, it enters high res monitor away from the bottom edge, a little annoying.
Still a better alternative then cursor getting stuck..

**Comment by Jawfin** [comment]
That must be a newer feature they've put in, it's good to know.  I recall seeing this issue on their forums when I was researching the progress of the bug, so it would appear they've acted on it.  For instance, at this time this comment was posted: -
http://www.jawfin.net/?page_id=143&cpage=2#comment-15306
they hadn't resolved it.

**Comment by vanowm** [comment]
So, this issue was closed as in "not interested" ?

**Comment by Jawfin** [comment]
Hi there.
It was closed for these reasons: -
1. It was not an issue with the behaviour of NSM, but for a feature request which not how windows behaves.
2. There was a post that a solution for what was desired was found in DisplayFusion.
3. This comment details how this feature wasn't feasible: https://github.com/Jawfin/nsm/issues/1#issuecomment-296919019
4. It has been over a year since any post was made on this issue, the last one by me (meaning there was not any outstanding question).

As that comment cited states, this is a world away from what NSM is about, and a solution for this feature already exists.  I figured if no interest is shown in over a year, and by definition this is not an issue with NSM but a desire for another application, which already exists, it was probably time to close it!
